### ISSUE TITLE
Please provide the versions of all installation packages, especially timm

### ISSUE THREAD

**Issue by Archer-pro666** [naver-ai/rdnet#10]
Please provide the versions of all installation packages, especially timm

**Comment by dhkim0225** [comment]
Please refer to [TRAINING.md](https://github.com/naver-ai/rdnet/blob/main/TRAINING.md) and [pyproject.toml](https://github.com/naver-ai/rdnet/blob/main/pyproject.toml).

[detection readme](https://github.com/naver-ai/rdnet/blob/main/detection/README.md)
[segmentation readme](https://github.com/naver-ai/rdnet/blob/main/segmentation/README.md)
