### ISSUE TITLE
Questions about channel re-scaling approach

### ISSUE THREAD

**Issue by DennisInTw** [naver-ai/rdnet#14]
Hello,
Thanks for your good work.
I have two questions about the proposed channel re-scaling approach.

Q1)
It describes that this work merges channel layer-scale [76] and an effective squeeze-excitation network [48] as channel re-scaling approach.
But I cannot see how it merge. I can only see effective SE module below.
Could you please help give some advices about the proposed channel re-scaling?

https://github.com/naver-ai/rdnet/blob/6739093bf0af0ec53af163ff15e91d46d66dbe9e/rdnet/rdnet.py#L88

Q2)
Could you give some advices when to use ESE module?
Did you try to mix two block types like this scenario?
      **Block ==> ... ==> BlockESE ==> BlockESE ==> Block ==> ...**

Thanks.

**Comment by dhkim0225** [comment]
@DennisInTw 

The layer scale is defined in the following lines. 
https://github.com/naver-ai/rdnet/blob/6739093bf0af0ec53af163ff15e91d46d66dbe9e/rdnet/rdnet.py#L134-L135

In our experience, the ESE module is more efficient in stage 3 or stage 4. Performance improves when used in stage 1 or 2, but computation increases significantly.
RDNet already utilizes the ese module only in stages 3 and 4.
https://github.com/naver-ai/rdnet/blob/6739093bf0af0ec53af163ff15e91d46d66dbe9e/rdnet/rdnet.py#L385

Thank you.

**Comment by DennisInTw** [comment]
Thanks for your help.
