### ISSUE TITLE
Pretrained model in timm

### ISSUE THREAD

**Issue by ogencoglu** [naver-ai/rdnet#3]
Thanks for the great work!

Any plans to have pretrained models in `timm` repo so it can be used as an arbitrary backbone/embedder?

**Comment by dhkim0225** [comment]
It would be great if we could put RDNet in `timm` repo. After cleaning the code a little more, I'll open an issue about it.

**Comment by dhkim0225** [comment]
I released a package for you !

Please refer to https://github.com/naver-ai/rdnet/tree/feature/pip_package !

**Comment by ogencoglu** [comment]
Appreciated!

**Comment by dhkim0225** [comment]
Thx for opening an issue : https://github.com/huggingface/pytorch-image-models/issues/2241
