### ISSUE TITLE
To many Total mult-adds nums.

### ISSUE THREAD

**Issue by dobe0715** [naver-ai/rdnet#9]
Thank you for great research!

`model_t = timm.create_model('rdnet_tiny.nv_in1k', pretrained=False)`
`summary(model_t, input_size=(1, 3, 224, 224), device='cpu')`

Total params: 23,541,024
Trainable params: 23,541,024
Non-trainable params: 0
__Total mult-adds (Units.GIGABYTES): 78.87__
Input size (MB): 0.60
Forward/backward pass size (MB): 2651.23
Params size (MB): 94.15
Estimated Total Size (MB): 2745.99

![image](https://github.com/user-attachments/assets/11663004-cd23-4c79-a37b-7205e5b97cf6)

your paper assert that tiny model's FLOPs is 5GB. but it has 78GB.
Of course, i might not estimate right method.
But, i compare FLOPs with another models. than rdnet has much more.

I think, this code has some junk behavior. What do you think about this cause?

Thanks.

**Comment by dhkim0225** [comment]
Thank you for your interest in our work.

https://github.com/naver-ai/rdnet/blob/7bc6b007fe13f3474ee32baf1ed07eadd37d9b97/benchmark.py#L44-L48
I checked FLOPs with deepspeed 0.12.6 with a following command :
`python benchmark.py -b 128 --num-bench-iter 1000 --img-size=224 --fuser te --channels-last --bench infer -m rdnet_tiny`
![image](https://github.com/user-attachments/assets/6d944a49-9567-4979-a1d1-05d77cbb5c5f)

Please refer to [TRAINING.md](https://github.com/naver-ai/rdnet/blob/main/TRAINING.md)

**Comment by dobe0715** [comment]
Thank you for your response. 

I got the result by benchmark.py, too

Actually, my big problem is memory costs in my custom training.
I can't understand why using `timm.models.create_model` has different memory costs

`python benchmark.py -b 128 --num-bench-iter 100 --img-size=224 --fuser te --channels-last --bench train -m rdnet_tiny`
memory cost is :
![image](https://github.com/user-attachments/assets/a69e2a19-7f6f-467c-9d0f-3aa196ca853b)

but, when i use `timm.models.create_model('rdnet_tiny')` in custom training, memory cost is :
![image](https://github.com/user-attachments/assets/3ce717ea-884a-42f9-872e-4ddbf61a3348)

Thank you for reading my question!

**Comment by dhkim0225** [comment]
It is challenging to provide a definitive answer based solely on the described images. It would be beneficial to verify whether the `input image size has increased`, if any `fusing-related configurations have been applied (fuser te)`, and if the `channel-last` feature has been adapted. 

Thank you.

**Comment by dhkim0225** [comment]
Based on the provided information, it seems that the size value of `Estimated Total Size` is much smaller compared to the value shown by `nvidia-smi`. This seems a bit unusual. 

However, the results from `nvidia-smi` are highly reliable, this discrepancy may not pose a critical issue.

Noticing the output format of the summary you have shown closely resembles [torchinfo](https://github.com/TylerYep/torchinfo) (formerly [torch-summary](https://pypi.org/project/torch-summary/)), I carried out some tests as follows.

```python
import rdnet
import timm
from torchinfo import summary

model = timm.create_model("rdnet_tiny", pretrained=True)
batch_size = 128
summary(model, input_size=(batch_size, 3, 224, 224))
```
```
==============================================================================================================
Total params: 23,863,008
Trainable params: 23,863,008
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 646.23
==============================================================================================================
Input size (MB): 77.07
Forward/backward pass size (MB): 21213.95
Params size (MB): 95.44
Estimated Total Size (MB): 21386.46
==============================================================================================================
```

In my result, the value of `Estimated total size` is similar to `nvidia-smi` value.
Please check a summary method (or package) once more :)

Thank you.
